### ISSUE TITLE
Improve error message when the call to the parent class constructor is missing in a test fixture

### ISSUE THREAD

**Issue by giventocode** [microsoft/nutter#16]
Current behavior:
When a test fixture is created without calling the parent class initializer, e.g.:

```python
class TestTransform(NutterFixture):
  def __init__(self):
    pass
  def run_testcase(self):
    pass
  def assertion_testcase(self):
    assert True
```

An attribute error is displayed when executing the test:

```
AttributeError: 'TestTransform' object has no attribute 'data_loader'
....
```
Expected:

It should return a custom exception with a better error message, e.g.:

InitializationError: If you have an  ```__init__``` method in your test class, please include a call to initialize the parent class. For example: NutterFixture.__init__(self)

**Comment by tomconte** [comment]
Hi folks :-) Stumbled on that issue yesterday, it looks like it is fixed but not released, right?

**Comment by giventocode** [comment]
Hey @tomconte, that is right. The fix will be included in the next release - within next couple of weeks.
