### ISSUE TITLE
Must the run and assertion functions have the same name?

### ISSUE THREAD

**Issue by omri374** [microsoft/nutter#35]
Looks like nutter only works when two functions are defined:
```
def run_test():
  pass

def assert_test():
  pass

When the two functions have different endings, the user gets an exception. However, it makes sense to run the notebook once and then test multiple assertions. Is this use case supposed?

**Comment by giventocode** [comment]
This is correct. We have are planning to change this behavior and allow multiple assertions without an associated run method.

**Comment by RobBagby** [comment]
Hi Omri,
Nutter 0.1.33 was just released that releases the requirement to have a ```run_<test_case_name>``` along with the ```assertion_<test_case_name>```.  Removing this requirement allows you to have multiple assertions.  Essentially, the pattern is to execute your notebook under test in the ```before_all``` method.  You then have multiple ```assertion_``` methods.
I am closing the issue.  Please let us know if you have further issues.
