### ISSUE TITLE
Plans to augment test report?

### ISSUE THREAD

**Issue by sebastus** [microsoft/nutter#36]
![image](https://user-images.githubusercontent.com/1289132/81192104-bbbe0f80-8fb1-11ea-8acb-d1bebfb0a5d1.png)

What plans are there to augment the xml output so a test title and error message can be sent along?

**Comment by giventocode** [comment]
The error message and the details of the error should be included when there's a failure. Are you seeing something different?

**Comment by sebastus** [comment]
To this point I'm asserting successes and would like each one to have a title so the report says more about which tests were done besides a test_name.

**Comment by giventocode** [comment]
Can you please elaborate on what you expect on the title? The title is the nutter test case name.  A test case in nutter is a combination of a ```run_<test_case_name>``` and an assertion ```assertion_<test_case_name>```.  

We map the nutter test cases to JUnit test cases.  The net result is that for each nutter test case you will see a test entry in Azure DevOps (without the prefixes, run_.. and assertion_...).  If any nutter test case fails, we map the stack trace and the URL to the run page that provides more details.   Please let us know if we are missing something.
