### ISSUE TITLE
Documentation issue : Incorrect commands to set the environment variable

### ISSUE THREAD

**Issue by Praxkv1** [microsoft/nutter#42]
Below command wont run in **windows power shell** to set the environment variable

```
$env DATABRICKS_HOST="HOST"
$env DATABRICKS_TOKEN="TOKEN"
```

Instead it should be like below
```
$env:DATABRICKS_HOST="HOST"
$env:DATABRICKS_TOKEN="TOKEN"
```

**Comment by giventocode** [comment]
Thanks for the feedback.

**Comment by Praxkv1** [comment]
> Thanks for the feedback.

Is there a way i can contribute to this repo? I fixed the issue in my local branch and when i try to push my branch to remote it says i dont have sufficient access to do so. How do i actually create a PR for this repo?

**Comment by Praxkv1** [comment]
> Thanks for the feedback.

Created below PR to fix this issue
[https://github.com/microsoft/nutter/pull/44](url)

**Comment by giventocode** [comment]
Doc updated.
