### ISSUE TITLE
Assertions on notebook context

### ISSUE THREAD

**Issue by csuriano23** [microsoft/nutter#69]
Is there a way to make assertions on a notebook context "imported" with `dbutils.notebook.run("some_nb", 600, {})`?

In order to clarify, I can have a notebook some_nb.py like this:

```python
# Databricks notebook source
# some_nb.py
MY_VAR = 100
```

and my nutter notebook test_some_nb.py:

```python
# Databricks notebook source
# test_some_nb.py

# MAGIC %pip install nutter

# COMMAND ----------

from runtime.nutterfixture import NutterFixture

class TestSomeNb(NutterFixture):
    def before_all(self):
        dbutils.notebook.run("some_nb", 600, {})

    def assertion_value(self):
        assert MY_VAR == 100

# COMMAND ----------

result = TestSomeNb().execute_tests()
result.exit(dbutils)
```

This is obviously broken, since MY_VAR isn't in the scope of "test_some_nb.py", even though I have run the dependant notebook.

Is there a way to this without explicitly running the notebook with the following command?

```python
# COMMAND ----------

# MAGIC %run ./some_nb
```

**Comment by giventocode** [comment]
You could wrap your constants or assertions in a library. Install the library in the cluster and import it.

**Comment by csuriano23** [comment]
I see, but I'd prefer not to restructure my application for testing and there are some actions in notebooks that can't be packaged into a python library. If there isn't some other way, I'd leave the run command
